### ISSUE TITLE
Ammo voting at start of the map not while in progrees

### ISSUE THREAD

**Issue by meganfoxxed** [The-Purgery/The-Purgery#12]
Many times people are voting LG  ammo to 200 from 150 mid way through the game, if this is to be part of a voteable option can we have this to be voteable only before the match starts and then it can reset post match

**Comment by tjone270** [comment]
The following `callvote` commands now function in the warmup game state only:
* `glammo`
* `lgammo`
* `lgdamage`
* `rgdamage`

Having the value reset at the end of the match is certainly possible but I don't want to do this. 

Perhaps we could have a `!changes` command or similar which lists out the active differences voted in compared to the standard ruleset.
If this is a good idea, please submit a new issue using the Feature Request template.

**Comment by meganfoxxed** [comment]
Appears to be a bug with infinite ammo getting enabled every game once it has started. the /cv infiniteammo can be called at any time by any player even during a match.
