### ISSUE TITLE
Update the map rotation

### ISSUE THREAD

**Issue by BigCTheYeti** [The-Purgery/The-Purgery#19]
remove unplayed or pointless maps like campgrounds blue, gridworks, delerium, wintersedge etc. from regular map rotation
add some often-voted favourites to map rotation e.g. ts_ca1, uprise, swift, q3wsh22(?) and so on

**Comment by meganfoxxed** [comment]
Purger will be working on this in a way it we be exposed to some of the admins and something we can look at doing . See #9 for more details

**Comment by tjone270** [comment]
Duplicate of #13 however as per @meganfoxxed comment we will be exposing this at a moderator level.
