### ISSUE TITLE
Infinite Ammo Bug, possibly linked to Issue #12

### ISSUE THREAD

**Issue by kev88au** [The-Purgery/The-Purgery#21]
## Description
There is a bug where infinite ammo is enabled at the start of each game. Players need to call a vote to disable it each time. After a map change, players ready up, and infinite ammo is enabled again.

## Steps to Reproduce
1. Everyone readies up via F3.
2. Notice that infinite ammo is on.
3. Players call a vote to disable infinite ammo.
4. After a map change, players press F3 to ready up.
5. Infinite ammo is enabled again.

## Expected Behavior
Infinite ammo should remain disabled once it has been voted off.

## Actual Behavior
Infinite ammo is enabled at the start of each game, even after being voted off in the previous game.

## Validation
This issue has been confirmed by Josh. He logged in and passed a vote to disable infinite ammo, but it was enabled again in the following game.

## Possible Link to Issue #12
This issue might be linked to Issue #12, where changes to ammo were made voteable only during the warmup game state. The infinite ammo bug could be a side effect of these changes.

**Comment by tjone270** [comment]
A race condition was introduced during a modification to minqlxtended I made recently and was not related to changes made in #12. The condition affected handling the gamestate transition to GAME_COUNTDOWN from any other gamestate. 

It's on the transition to ``GAME_COUNTDOWN`` that `g_infiniteAmmo` is set to `0` on the server, irrespective of previous votes. This was not being handled.

This race condition has now been resolved and a demonstration of the intended behaviour of infinite ammo is below:
https://github.com/The-Purgery/The-Purgery/assets/6151202/de50da7f-1ec7-4088-80d5-089b9d4ab9e1
