### ISSUE TITLE
Consolidation and Renaming of Quake Live Servers

### ISSUE THREAD

**Issue by kev88au** [The-Purgery/The-Purgery#22]
#### Consolidation and Renaming of Quake Live Servers

**Note:** 
I've included dots between Hash and Numbers to prevent GitHub linking to other issues. 

**Objective:** 
Reducing the number of active servers and renaming them for better clarity will streamline the server list and improve ease of use.

**Proposal:**

1. **Server Reduction:**
   - **Primary Public Server:**
     - **#.0 The Purgery - PQL (1) - Unlimited Clan Arena**
       - This server is the most populated and should be retained as the main public server.
   
   - **Secondary Server for Smaller Groups:**
     - **#.1 The Purgery - PQL (2) - Unlimited Clan Arena**
       - This server can be used for smaller groups who want games outside the busy main server.
   
   - **Dedicated VQL Server:**
     - **#.4 The Purgery - VQL (1) - Unlimited Clan Arena**
       - This server will cater to VQL players. Though it may remain empty, it serves as an alternative in the region.

2. **Server Shutdown:**
   - Shut down all other servers to consolidate the player base and reduce confusion. For ad-hoc fun, players can vote for different game types in the secondary public server and reset as needed.

3. **Web Portal for Admins:**
   - Implement a feature in the web overhaul allowing administrators to spawn or shut down servers via a web portal for organized events (e.g. 3v3 Tournament). 

4. **Server Renaming:**
   -  Propose to rename the servers to follow a clear and consistent format. Suggested format:
     ```
     Sydney | The Purgery - #.1 - PQL - Clan Arena
     Sydney | The Purgery - #.2 - PQL - Custom
     Sydney | The Purgery - #.3 - VQL - Clan Arena
     Sydney | The Purgery - #.4 - VQL - Duel
     ```
   - This format will group The Purgery servers together and reduce confusion when referencing server numbers.
   - Suggest allowing game-type voting on the custom server (Freeze, Vampiric, etc.) 

**Reasoning:**
- **Improved User Experience:**
  - With fewer servers, players can easily find the server they want to join, reducing fragmentation of the player base.
  
- **Clarity in Communication:**
  - The proposed naming convention will eliminate confusion about which server is being referred to, especially when using numbers in server names.
  -  Terms like "#.0 The Purgery - PQL (1)" seem confusing. Is this Purgery 0, or Purgery 1?

**Comment by Slider-Whistle** [comment]
No Deathmatch/FFA? I know that shit's never populated but it's got a place within Q3

**Comment by tjone270** [comment]
The servers were reorganised and renamed during the implementation of minqlxtended.
![image](https://github.com/user-attachments/assets/9dfac4ec-e59e-4f9c-9eef-3fcaea71951b)
If further servers are required, open another issue please.
