### ISSUE TITLE
Disable teamsize voting after 9 total rounds

### ISSUE THREAD

**Issue by meganfoxxed** [The-Purgery/The-Purgery#25]
"/cv team size" command should be disabled after a total of 9 rounds have been played, following feedback from a recent Discord poll. This decision aligns with previous poll results where 8 or 9 rounds were preferred. Moderators will still have access to the "!ts" command for necessary adjustments

We ran a poll months ago and was hoping this could be implemented, has been sometime so we re ran it.

**Comment by tjone270** [comment]
This has been implemented - if the game type is Clan Arena, and a vote to alter the teamsize is called by any player after 8 rounds have elapsed, then we prevent the teamsize vote from being called entirely with the following message:
![image](https://github.com/user-attachments/assets/7b215f5b-3ac4-41f1-81f4-e3a4167e3fd2)

Moderators can continue to use the `!ts <size>` command to modify the teamsize, this command is completely unaffected by these changes.
