### ISSUE TITLE
Replace default billboards with a banner

### ISSUE THREAD

**Issue by joones105** [The-Purgery/The-Purgery#26]
![quakelive_steam exe Screenshot 2024 06 20 - 18 33 29 32](https://github.com/The-Purgery/The-Purgery/assets/123827673/bbfb86a3-1cd0-4e08-b7bf-492397085e8f)

is it possible to make it a slideshow?

make the purgery banner, some funny images
i could make these and perhaps theres some other designers around too

**Comment by tjone270** [comment]
I have always wanted to do this however at this stage it isn't possible on default maps unless we decompile them, modify them and then re-upload them, this would be a monumental task.

Sorry about that!

**Comment by tjone270** [comment]
Well, I figured it out and have now implemented on #0 this morning and will leave on for now unless anything goes wrong - any feedback on the custom assets - please let me know. 

Only took 9 years to figure this out - I've always wanted to do it! Have custom model capabilities now as well without having to be an impure server along with the ability to replace other textures (I've done this in some cases already - check out the Chat icon!)
![banner2x1](https://github.com/The-Purgery/The-Purgery/assets/6151202/e5569b04-2c25-46ff-b4a1-8b40e8a0f962)
![image](https://github.com/The-Purgery/The-Purgery/assets/6151202/5a54b1d8-522a-467c-8a8c-8ac898f91b3f)
![image](https://github.com/The-Purgery/The-Purgery/assets/6151202/5eb36ad9-8435-4c01-9089-898fa68ed885)

**Comment by tjone270** [comment]
Implemented on all Purgery servers now.
