### ISSUE TITLE
After using the !ts command, the queue becomes disrupted/broken

### ISSUE THREAD

**Issue by meganfoxxed** [The-Purgery/The-Purgery#28]
Sometimes, when you use the !ts size command to increase the team size while people are in the queue, the only way to join is by requeuing, which causes those who were in the queue first to lose their spots.

**Comment by kev88au** [comment]
Yeah, I’m not sure what causes it to get stuck, although I’ve found that doing !red # of whoever is first in the queue will let them have their spot, and then distribute everyone else. 

It’s not ideal, but it is a workaround.

**Comment by tjone270** [comment]
I've deployed some fixes to this which should allow the queueing system to be 'notified' properly when changes to the teamsize occur via either vote or via `!ts <size>`.
