### ISSUE TITLE
Automatic command listing and web-based documentation

### ISSUE THREAD

**Issue by meganfoxxed** [The-Purgery/The-Purgery#29]
Provide a detailed breakdown and list of documentation for various !commands, including those available to managers, moderators, and special players. This information should be accessible on the website and can be added to the Discord server if necessary.

**Comment by tjone270** [comment]
The documentation capability for commands has been completed. The website has been updated to have a "[Commands](https://thepurgery.com/commands)" button in the navigation bar:
![image](https://github.com/user-attachments/assets/9e4d53d3-34cf-4ce1-bf48-12c672480157)

Not signing in to the website will allow commands with permission level 0 to be visible, while signing in will show all commands at your permission level, and all those below.

Each listed command still needs better documentation though - so I'll leave this open to ensure we get this finished. If anyone has suggestions or can contribute documentation, please advise.

**Comment by tjone270** [comment]
Completed documentation of all commands. Closing this request now.
