### ISSUE TITLE
Workshop items update

### ISSUE THREAD

**Issue by joones105** [The-Purgery/The-Purgery#31]
Theres heaps of stuff on steam workshop that has been created by the quake community and seems interesting. Would it be possible to upload some of these to the server? Mostly maps and skins. Ive been checking some of these out and here are the results:

https://steamcommunity.com/sharedfiles/filedetails/?id=2888269948&searchtext=nohalls
nohalls.pk3 -- its an overkill remix with half of the map cut off. This one is being played in EU VCA servers and Im sure it would get decent playtime in The Purgery aswell

Next maps up are just personal choices and need testing
https://steamcommunity.com/sharedfiles/filedetails/?id=3237045108&searchtext=dogegrounds
https://steamcommunity.com/sharedfiles/filedetails/?id=3101188892&searchtext=asylumplus
https://steamcommunity.com/sharedfiles/filedetails/?id=2144391961&searchtext=reactor  -- Ive seen this one being played
https://steamcommunity.com/sharedfiles/filedetails/?id=2926820702&searchtext=chamber
https://steamcommunity.com/sharedfiles/filedetails/?id=1317503170&searchtext=overchad

**Comment by tjone270** [comment]
Hi @joones105 - all those items have been added and included in the map pool, this will take effect in approx. 24 hours.
