### ISSUE TITLE
Make "xxx called a vote" show up red

### ISSUE THREAD

**Issue by k3nnyq3** [The-Purgery/The-Purgery#34]
Title says it all. Easy thing if possible at all. Makes it heaps easier to track who called a vote. Can be useful in many situations.

**Comment by tjone270** [comment]
Hi @k3nnyq3, I've not implemented this as the `Purger called a vote` message is built-in and harder to override.

What I have done is created `!lastvotes` which shows the last 10 votes called as follows:
![image](https://github.com/user-attachments/assets/f8ae9996-7370-44d1-a09c-0d133e1f7c19)

This command is not locked and (I hope) achieves the outcome you desire.
