### ISSUE TITLE
Remove custom stuff off purgery servers

### ISSUE THREAD

**Issue by Aeol1** [The-Purgery/The-Purgery#36]
Whenever you join a purgery server you cannot join other servers after and I think this hurts the health of QL a little as I've seen new players refund the game because they think the game is bugged. Also it's just annoying having to close the game and open it up again just to join another server. Others have agreed with me on discord. I'm not sure if having a couple of custom images and such is worth that tbh.

**Comment by tjone270** [comment]
Hi @Aeol1, while I understand the frustration of having to relaunch Quake Live in some instances when connecting to other servers, reverting the modifications on The Purgery would remove several optimisations and improvements made on Quake Live servers (not just the new banners and visual updates.)

It's something I'm still looking into as the game mentions 'Unpure PK3s' as the error but the purity of the PK3s is definitely not the issue - there is a bug somewhere within the way Quake Live handles/caches PK3s between server map changes/connecting to other servers which causes what I'm calling a 'PK3 bias'. 

I will attempt to rectify this root issue as time permits, however in the interim I will not make any changes.
