### ISSUE TITLE
Fix the vote state tracking functionality in `custom_votes.py`

### ISSUE THREAD

**Issue by tjone270** [The-Purgery/The-Purgery#4]
•	Fix the game logic whereby vote execution status is not reset correctly post-execution of the vote. custom_votes.py will contain the issue.

**Comment by meganfoxxed** [comment]
This seems to now be making it hard to /cv infiniteammo off , as this gets stuck in the same state until the next map. Referring to issue #21 #12

**Comment by tjone270** [comment]
@meganfoxxed this is not related.

**Comment by tjone270** [comment]
Fixed.
