### ISSUE TITLE
Restrict `!selo`/`!elos` to administrators only.

### ISSUE THREAD

**Issue by tjone270** [The-Purgery/The-Purgery#6]
•	Disable the !elos and !selo commands/restrict to admins.

**Comment by tjone270** [comment]
Restricted the `!elos`/`!selo`/`!ratings` commands to permission level 2 or above.

**Comment by meganfoxxed** [comment]
noted this happening now in game, Bribs was just spamming each persons client number to see them all. !elo 1 , !elo 3 , !elo 3 etc. Could we introduce a cooldown between this command?

**Comment by tjone270** [comment]
Investigating now...

**Comment by tjone270** [comment]
Changed my original revision to behave as follows:
1. `!elos`/`!selo`/`!ratings` now returns a message when run by a non-permission-level 2 player stating it's not permitted.
2. `!elo` by itself still works for players retrieving their own rating, but running `!elo <id>` is restricted to permission level 2, with an explanatory message. 

Changes will take effect after 24 hours.
