### ISSUE TITLE
Configure a TTL on manually-set ELO values

### ISSUE THREAD

**Issue by tjone270** [The-Purgery/The-Purgery#7]
•	Manually set ELO values have a TTL of 7 days.

**Comment by kev88au** [comment]
For the benefit of anyone else reading this who wasn't at the LAN. 

The default ELO in Quake is 900, which is often higher than it should be for new accounts. Usually, it only takes a few games for this to adjust accurately. Admins have the ability to manually set ELOs, but once set, the server will use that ELO until it is manually removed.

We are discussing a backend change that will ensure any ELO manually set by an admin will only last for 7 days before defaulting back to the QLstats ELO ratings. During this time, ELO calculation will continue in the background and be submitted to QLstats, ensuring the rating remains up-to-date, so when the manual adjustment is removed, it should be an accurate reflection of the players skill.

**Comment by tjone270** [comment]
Add this functionality to minqlxtended as per commit:
https://github.com/tjone270/minqlxtended-plugins/commit/346b0866d7a6fe57a678039c0c7ff5064fdd44a0

@kev88au and others, how long should a manually-set rating be active for, before expiring?

**Comment by kev88au** [comment]
It’s mostly a problem for random accounts that start with 900 Elo and play significantly better or worse. 

Anyone who manually sets an ELO would be doing so, hoping to match damage delivered against others playing. I think that seven days is a good number.  

It’s long enough that it solves the immediate problem of a player being -290 elo and getting a heavily stacked team to balance it out. Yet, also an appropriately timed failsafe against forgetting to remove it.

**Comment by tjone270** [comment]
604800 seconds it is, I'll configure now.

**Comment by tjone270** [comment]
This was configured and has been in-place for some time. A web control panel was built to cover monitoring of these temporary ratings and their expirations.
![image](https://github.com/user-attachments/assets/e273d20a-6fad-4698-9294-8a77a0044fae)

Upon creating this screenshot I found an issue with the way expirations are implemented - this is now fixed and working correctly.
